### ISSUE TITLE
ConcurrentModificationException exception occurs when importing network

### ISSUE THREAD

**Issue by abargnesi** [jsongraph/jgf-app#1]
A `ConcurrentModificationException` error occurs when importing a JSON Graph format. The user will see a message popup indicating a "null" after importing.

The stacktrace reported is:

```
java.util.ConcurrentModificationException
        at java.util.IdentityHashMap$IdentityHashMapIterator.nextIndex(IdentityHashMap.java:732)
        at java.util.IdentityHashMap$EntryIterator.next(IdentityHashMap.java:838)
        at java.util.IdentityHashMap$EntryIterator.next(IdentityHashMap.java:832)
        at org.cytoscape.ding.impl.AbstractDViewModel.clearVisualProperties(AbstractDViewModel.java:198)
        at org.cytoscape.view.vizmap.internal.ApplyToNetworkHandler.apply(ApplyToNetworkHandler.java:77)
        at org.cytoscape.view.vizmap.internal.VisualStyleImpl.apply(VisualStyleImpl.java:157)
        at org.cytoscape.task.internal.loadnetwork.GenerateNetworkViewsTask.run(GenerateNetworkViewsTask.java:98)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:337)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

This is an [issue](http://code.cytoscape.org/redmine/issues/2548) in Cytoscape that was fixed in Cytoscape 3.1.1.

The `Cytoscape-API-Compatibility` manifest header will be set to `3.1`, but keep in mind that this error can occur on Cytoscape 3.1.0 and previous.

**Comment by abargnesi** [comment]
Set compatibility header in 61c04e853bc747d3d6deaf5b3a0889280a195049.

This error can occur if using Cytoscape 3.1.0.
